name: Deploy Fastshop Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 24700
          script: |
            # 1. Di chuyển vào đúng thư mục dự án trên server của bạn
            cd ~/huan-compose-app/fastshop
            
            # 2. Kéo source code mới nhất từ GitHub về
            git pull origin main
            
            # 3. Di chuyển vào thư mục chứa file docker-compose.yml
            cd deployment
            
            # 4. Hạ các container cũ xuống để giải phóng tài nguyên
            docker compose down
            
            # 5. Khởi động lại và ép build lại image mới từ code vừa pull
            docker compose up -d --build
